spring.application.name=book-app

spring.datasource.url=jdbc:postgresql://localhost:5432/sandbox_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.max-lifetime=1800000